apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-lxgu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ssadeghi-tenant/partner-catalog/partner-catalog-lxgu@sha256:c0354e6ed73dd773512ea51a80f605c72c4d71739bc727e629fb384d0fac0cb7
        name: my-java-springboot
        resources: {}
status: {}
